### ISSUE TITLE
Error: Cannot find module './generator'

### ISSUE THREAD

**Issue by AaronHolbrook** [spatie/tailwind-safelist-generator#2]
First off, I just want to say this tool is a fantastic idea and very timely - I was just looking for something like this!

After installing and attempting to run, I am immediately presented with the following error:

`[webpack-cli] Error: Cannot find module './generator'`

It appears that the main file is including a dependency that isn't specified in the package itself?

Full error log:

```
npm run dev

> dev
> npm run development


> development
> mix

[webpack-cli] Error: Cannot find module './generator'
Require stack:
- /Users/user/dev/sites/site/node_modules/tailwind-safelist-generator/index.js
- /Users/user/dev/sites/site/tailwind.config.js
- /Users/user/dev/sites/site/node_modules/tailwindcss/lib/index.js
- /Users/user/dev/sites/site/node_modules/laravel-mix-tailwind/index.js
- /Users/user/dev/sites/site/webpack.mix.js
- /Users/user/dev/sites/site/node_modules/laravel-mix/setup/webpack.config.js
- /Users/user/dev/sites/site/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/user/dev/sites/site/node_modules/webpack-cli/lib/bootstrap.js
- /Users/user/dev/sites/site/node_modules/webpack-cli/bin/cli.js
- /Users/user/dev/sites/site/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/user/dev/sites/site/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/user/dev/sites/site/node_modules/tailwind-safelist-generator/index.js:3:19)
    at Module._compile (/Users/user/dev/sites/site/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/dev/sites/site/node_modules/tailwind-safelist-generator/index.js',
    '/Users/user/dev/sites/site/tailwind.config.js',
    '/Users/user/dev/sites/site/node_modules/tailwindcss/lib/index.js',
    '/Users/user/dev/sites/site/node_modules/laravel-mix-tailwind/index.js',
    '/Users/user/dev/sites/site/webpack.mix.js',
    '/Users/user/dev/sites/site/node_modules/laravel-mix/setup/webpack.config.js',
    '/Users/user/dev/sites/site/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/user/dev/sites/site/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/user/dev/sites/site/node_modules/webpack-cli/bin/cli.js',
    '/Users/user/dev/sites/site/node_modules/webpack/bin/webpack.js'
  ]
}
```

**Comment by sebastiandedeyne** [comment]
Sorry for the late catch, was on vacation. I tagged a bugfix release!
